// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4aVqtrBgX-qPNxVALi1SWDYVi6eiN3Q',
    appId: '1:123744625570:web:daa03ad2f34852f4f8c8fb',
    messagingSenderId: '123744625570',
    projectId: 'food-delivery-app-99354',
    authDomain: 'food-delivery-app-99354.firebaseapp.com',
    storageBucket: 'food-delivery-app-99354.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnQFZtC6E6gQ1PfYJtV0E8HH7o1kACls',
    appId: '1:123744625570:android:5a8eb19eca77ffc3f8c8fb',
    messagingSenderId: '123744625570',
    projectId: 'food-delivery-app-99354',
    storageBucket: 'food-delivery-app-99354.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-XU8of08aTZFws6J022aoy09uUaCoWWU',
    appId: '1:123744625570:ios:1ddfbae8f975f730f8c8fb',
    messagingSenderId: '123744625570',
    projectId: 'food-delivery-app-99354',
    storageBucket: 'food-delivery-app-99354.appspot.com',
    iosClientId: '123744625570-7k4mtvbq845p8fvm1qtcob5d87pu23en.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-XU8of08aTZFws6J022aoy09uUaCoWWU',
    appId: '1:123744625570:ios:1ddfbae8f975f730f8c8fb',
    messagingSenderId: '123744625570',
    projectId: 'food-delivery-app-99354',
    storageBucket: 'food-delivery-app-99354.appspot.com',
    iosClientId: '123744625570-7k4mtvbq845p8fvm1qtcob5d87pu23en.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFoodDelivery',
  );
}
